import Link from "next/link";
import { notFound } from "next/navigation";
import { relayJson } from "@/lib/upstream";

export const dynamic = "force-dynamic";

function money(value?:number|null,currency="EUR"){if(!Number.isFinite(Number(value)))return"Τρέχουσα τιμή στο AliExpress";try{return new Intl.NumberFormat("el-GR",{style:"currency",currency,maximumFractionDigits:2}).format(Number(value))}catch{return`${value} ${currency}`}}

export default async function ProductDecisionPage({params}:{params:Promise<{research:string;product:string}>}){
 const{research,product}=await params;const{status,data}=await relayJson("nhma-engagement-v4",{action:"get_research",token:research},"POST");const snapshot=status===200&&(data as any)?.research?(data as any).research:null;if(!snapshot)notFound();const p=(Array.isArray(snapshot.products)?snapshot.products:[]).find((x:any)=>String(x.productId)===decodeURIComponent(product));if(!p)notFound();
 return <main className="decision-page"><header className="catalog-header"><Link href="/" className="catalog-brand"><span className="brand-mark">AI</span> <b>AIgora</b></Link><Link href={`/brief/${research}`}>Η έρευνά μου →</Link></header><section className="decision-hero"><div className="decision-media">{p.imageUrl?<img src={p.imageUrl} alt={p.title||"Προϊόν"}/>:<span>◫</span>}<b>AI VERIFIED</b></div><div className="decision-copy"><p className="eyebrow">PRODUCT DECISION · 🇪🇺 {p.warehouseCountry}</p><h1>{p.title}</h1><p className="decision-price">{money(p.price,p.currency)}</p><div className="decision-score"><span>AI Match</span><b>{p.matchScore!=null?`${p.matchScore}/100`:"Verified"}</b></div><p className="decision-why">{p.why}</p><div className="decision-cta-row">{p.trackingPath?<a className="decision-primary" href={`${p.trackingPath}?source=product_detail`} target="_blank" rel="sponsored noopener noreferrer">Δες την τρέχουσα προσφορά →</a>:<span>Tracking unavailable</span>}<Link href={`/compare/${research}?ids=${encodeURIComponent(p.productId||"")}`}>Σύγκρινε</Link></div><small className="disclosure">Affiliate link · η προμήθεια δεν καθορίζει το semantic ranking.</small></div></section><section className="decision-grid"><article><p className="eyebrow">WHY IT RANKED</p><h2>Γιατί ξεχώρισε</h2>{(p.decision?.strengths||[]).map((x:string)=><p className="decision-good" key={x}>✓ {x}</p>)}</article><article><p className="eyebrow">FULL DISCLOSURE</p><h2>Τι να προσέξεις</h2>{(p.decision?.limitations||[]).length?(p.decision.limitations||[]).map((x:string)=><p className="decision-caution" key={x}>⚠ {x}</p>):<p>Δεν έχει καταγραφεί συγκεκριμένος περιορισμός πέρα από τα unknown fields.</p>}</article><article><p className="eyebrow">VERIFIED</p><h2>Τι ελέγξαμε</h2>{(p.decision?.verifiedFields||[]).map((x:string)=><p key={x}>✓ {x}</p>)}</article><article><p className="eyebrow">UNKNOWN</p><h2>Τι δεν θα μαντέψουμε</h2>{(p.decision?.unknownFields||[]).length?(p.decision.unknownFields||[]).map((x:string)=><p key={x}>— {x}</p>):<p>Δεν υπάρχουν δηλωμένα unknown fields.</p>}</article></section><section className="warehouse-proof"><div><p className="eyebrow">EU WAREHOUSE PROOF</p><h2>Δεν είναι badge χωρίς απόδειξη.</h2><p>Το προϊόν εμφανίστηκε σε explicit AliExpress ship-from filter για <b>{p.warehouseCountry}</b>.</p></div>{p.warehouseProofUrl&&<a href={p.warehouseProofUrl} target="_blank" rel="noopener noreferrer">Άνοιξε το warehouse evidence ↗</a>}</section><section className="decision-reviews"><p className="eyebrow">BUYER FEEDBACK</p><h2>Αξιολογήσεις χωρίς κατασκευασμένα quotes.</h2><p>Δείχνουμε μόνο feedback metrics που επέστρεψε η πηγή. Δεν δημιουργούμε “σύνοψη reviews” αν δεν έχουμε το πραγματικό review text.</p>{p.trackingPath&&<a href={`${p.trackingPath}?source=reviews`} target="_blank" rel="sponsored noopener noreferrer">Δες τις πραγματικές αξιολογήσεις στο AliExpress →</a>}</section></main>
}
