"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { ChatMessage, ChatResponse, Product, SearchResponse } from "@/lib/types";

type Priority = "balanced" | "value" | "fast";
type SortKey = "recommended" | "price" | "rating" | "sales";
type Season = "bts" | "general";
type DemandItem = { label: string; query: string };
type DemandFamily = { id: string; icon: string; eyebrow: string; title: string; note: string; className: string; items: DemandItem[] };

const gradeOptions = ["Νηπιαγωγείο","Α΄ Δημοτικού","Β΄ Δημοτικού","Γ΄ Δημοτικού","Δ΄ Δημοτικού","Ε΄ Δημοτικού","ΣΤ΄ Δημοτικού","Α΄ Γυμνασίου","Β΄ Γυμνασίου","Γ΄ Γυμνασίου","Α΄ Λυκείου","Β΄ Λυκείου","Γ΄ Λυκείου"];

const btsDemands: DemandFamily[] = [
  { id:"carry", icon:"🎒", eyebrow:"ΚΑΘΗΜΕΡΙΝΗ ΜΕΤΑΦΟΡΑ", title:"Τσάντα & ό,τι μπαίνει μέσα", note:"Τα βασικά που κουβαλά κάθε μέρα — οργανωμένα ως μία οικογένεια.", className:"art-carry", items:[{label:"Σχολική τσάντα",query:"εργονομική σχολική τσάντα με ενισχυμένη πλάτη"},{label:"Κασετίνα",query:"ανθεκτική σχολική κασετίνα με ένα ή δύο ανοίγματα"},{label:"Παγούρι",query:"παγούρι νερού για σχολείο leakproof"},{label:"Lunch bag",query:"ισοθερμική τσάντα φαγητού για σχολείο"}] },
  { id:"study", icon:"📚", eyebrow:"ΜΕΛΕΤΗ ΣΤΟ ΣΠΙΤΙ", title:"Γραφείο που βοηθά να συγκεντρωθεί", note:"Φως, τάξη και μικρές λύσεις για λιγότερη τριβή στο διάβασμα.", className:"art-study", items:[{label:"Φωτισμός γραφείου",query:"ρυθμιζόμενο φωτιστικό γραφείου για μαθητή"},{label:"Οργάνωση γραφείου",query:"desk organizer για μαθητικό γραφείο"},{label:"Βάση βιβλίου",query:"ρυθμιζόμενη βάση βιβλίου για μελέτη"},{label:"Timer μελέτης",query:"study timer desk για συγκέντρωση"}] },
  { id:"tech", icon:"💻", eyebrow:"TECH READY", title:"Tech για μάθημα και εργασία", note:"Πρώτα η πραγματική χρήση και μετά τα specs — με αυστηρό budget.", className:"art-tech", items:[{label:"Laptop",query:"laptop για μαθητή σχολείο και καθημερινή εργασία"},{label:"Ακουστικά",query:"άνετα headphones για online μάθημα και μελέτη"},{label:"Πληκτρολόγιο",query:"compact keyboard για μαθητή και γραφείο"},{label:"Laptop stand",query:"ρυθμιζόμενη βάση laptop για γραφείο"}] },
  { id:"food", icon:"🥪", eyebrow:"LUNCH & HYDRATION", title:"Φαγητό και νερό χωρίς διαρροές", note:"Πρακτική μεταφορά, εύκολο καθάρισμα και καθημερινή αντοχή.", className:"art-food", items:[{label:"Lunch box",query:"στεγανό lunch box για σχολείο"},{label:"Ισοθερμική τσάντα",query:"ισοθερμική lunch bag για σχολείο"},{label:"Παγούρι",query:"leakproof water bottle για σχολείο"},{label:"Snack δοχεία",query:"μικρά στεγανά δοχεία snack για σχολείο"}] },
  { id:"organize", icon:"✓", eyebrow:"ΜΗΝ ΞΕΧΑΣΟΥΜΕ ΤΙΠΟΤΑ", title:"Οργάνωση σχολικής καθημερινότητας", note:"Μικρά αντικείμενα που λύνουν επαναλαμβανόμενα καθημερινά προβλήματα.", className:"art-organize", items:[{label:"Ετικέτες ονόματος",query:"name labels για σχολικά αντικείμενα"},{label:"Θήκη καρτών",query:"student card holder lanyard"},{label:"Ντοσιέ οργάνωσης",query:"school document organizer folder"},{label:"Cable pouch",query:"small cable organizer pouch για μαθητή"}] },
  { id:"comfort", icon:"☁", eyebrow:"ΑΝΕΣΗ ΣΤΗΝ ΗΜΕΡΑ", title:"Μικρές λύσεις για πιο εύκολη μέρα", note:"Για μετακίνηση, βροχή, κούραση και τα μικρά απρόοπτα της σχολικής ημέρας.", className:"art-comfort", items:[{label:"Μικρή ομπρέλα",query:"compact lightweight umbrella για σχολική τσάντα"},{label:"Αδιάβροχο κάλυμμα",query:"waterproof backpack rain cover"},{label:"Θήκη γυαλιών",query:"hard glasses case για σχολική τσάντα"},{label:"Mini first-aid pouch",query:"small empty first aid pouch organizer"}] },
];

const generalDemands: DemandFamily[] = [
  { id:"home",icon:"⌂",eyebrow:"ΣΠΙΤΙ",title:"Λύσεις που γλιτώνουν χρόνο στο σπίτι",note:"Οργάνωση, καθαριότητα και πρακτικές καθημερινές αγορές.",className:"art-home",items:[{label:"Οργάνωση",query:"home organization storage solution"},{label:"Καθαριότητα",query:"useful home cleaning device"},{label:"Κουζίνα",query:"practical kitchen tool"}]},
  { id:"work",icon:"▣",eyebrow:"ΕΡΓΑΣΙΑ",title:"Πιο άνετο και λειτουργικό γραφείο",note:"Εργονομία, φωτισμός και παραγωγικότητα χωρίς περιττά gadgets.",className:"art-study",items:[{label:"Καρέκλα",query:"ergonomic office chair"},{label:"Φωτισμός",query:"adjustable office desk lamp"},{label:"Οργάνωση",query:"office desk organizer"}]},
  { id:"tech",icon:"⌘",eyebrow:"TECH",title:"Tech με βάση τη χρήση, όχι το hype",note:"Πες τι θέλεις να κάνεις και το search χτίζει το σωστό query.",className:"art-tech",items:[{label:"Laptop",query:"laptop for daily work"},{label:"Ακουστικά",query:"wireless headphones"},{label:"Smart home",query:"useful smart home device"}]},
  { id:"travel",icon:"→",eyebrow:"ΤΑΞΙΔΙ",title:"Πιο εύκολη μετακίνηση",note:"Οργάνωση αποσκευής, φόρτιση, άνεση και πρακτικά travel εργαλεία.",className:"art-carry",items:[{label:"Travel organizer",query:"travel organizer pouch"},{label:"Power bank",query:"compact power bank travel"},{label:"Packing cubes",query:"packing cubes travel"}]},
  { id:"kids",icon:"★",eyebrow:"ΠΑΙΔΙΑ",title:"Χρήσιμες επιλογές για οικογένεια",note:"Από οργάνωση έως δημιουργική απασχόληση, με σωστό product identity.",className:"art-organize",items:[{label:"Οργάνωση",query:"kids room organizer"},{label:"Δημιουργικό",query:"creative activity kit for kids"},{label:"Μεταφορά",query:"kids travel organizer"}]},
  { id:"gift",icon:"◇",eyebrow:"ΔΩΡΟ",title:"Δώρο με συγκεκριμένο budget",note:"Ξεκίνα από άνθρωπο, περίσταση και ποσό — όχι από ατελείωτες κατηγορίες.",className:"art-food",items:[{label:"Κάτω από €20",query:"useful gift under 20 euro"},{label:"Tech gift",query:"useful tech gift"},{label:"Για σπίτι",query:"useful home gift"}]},
];

function makeSessionId(){if(typeof crypto!=="undefined"&&"randomUUID" in crypto)return crypto.randomUUID();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,(c)=>{const r=Math.random()*16|0,v=c==="x"?r:(r&3|8);return v.toString(16)})}
function safeUrl(value?:string){try{const u=new URL(String(value||""));return u.protocol==="https:"||u.protocol==="http:"?u.href:null}catch{return null}}
function money(value?:number,currency="EUR"){if(!Number.isFinite(Number(value)))return null;try{return new Intl.NumberFormat("el-GR",{style:"currency",currency,maximumFractionDigits:2}).format(Number(value))}catch{return`${Number(value).toFixed(2)} ${currency}`}}
function feedback(product:Product){const raw=product.verification?.positiveFeedback??product.positiveFeedbackRate,n=Number(String(raw??"").replace("%",""));return Number.isFinite(n)?n:null}
function productRole(product:Product,list:Product[]){if(!list.length)return"Πρόταση";const cheap=[...list].filter(p=>Number.isFinite(Number(p.price))).sort((a,b)=>Number(a.price)-Number(b.price))[0],rated=[...list].filter(p=>feedback(p)!==null).sort((a,b)=>(feedback(b)??0)-(feedback(a)??0))[0];if(product.productId&&product.productId===list[0]?.productId)return"Καλύτερη αντιστοίχιση";if(cheap?.productId&&product.productId===cheap.productId)return"Πιο οικονομικό";if(rated?.productId&&product.productId===rated.productId)return"Υψηλή αξιολόγηση";return"Εναλλακτική"}
function composedQuery(base:string,grade:string,budget:string,priority:Priority,season:Season){const parts=[base,"αποστολή προς Ελλάδα"];if(season==="bts")parts.push(`για μαθητή ${grade}`);if(budget.trim())parts.push(`μέχρι ${budget.trim()} ευρώ`);if(priority==="value")parts.push("προτεραιότητα καλύτερη σχέση τιμής και ποιότητας");if(priority==="balanced")parts.push("προτεραιότητα αξιοπιστία και καλή τιμή");if(priority==="fast")parts.push("παράδοση το πολύ 10 ημέρες");return parts.join(", ")}

export function CommerceShell({season}:{season:Season}){
 const demands=season==="bts"?btsDemands:generalDemands;
 const [sessionId,setSessionId]=useState("");const[grade,setGrade]=useState("Α΄ Γυμνασίου");const[budget,setBudget]=useState("");const[priority,setPriority]=useState<Priority>("balanced");const[query,setQuery]=useState("");const[products,setProducts]=useState<Product[]>([]);const[understood,setUnderstood]=useState("");const[resultQuery,setResultQuery]=useState("");const[activeDemand,setActiveDemand]=useState("");const[clarification,setClarification]=useState<{question:string;options:string[]}|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[sort,setSort]=useState<SortKey>("recommended");const[saved,setSaved]=useState<Product[]>([]);const[compare,setCompare]=useState<Product[]>([]);const[imageData,setImageData]=useState<string|null>(null);const[imageName,setImageName]=useState("");const[live,setLive]=useState(false);const[chatOpen,setChatOpen]=useState(false);const[chatting,setChatting]=useState(false);const[chatInput,setChatInput]=useState("");const[chatMessages,setChatMessages]=useState<ChatMessage[]>([]);const[suggested,setSuggested]=useState<string[]>([]);const[compareOpen,setCompareOpen]=useState(false);const fileRef=useRef<HTMLInputElement>(null);const resultsRef=useRef<HTMLElement>(null);
 useEffect(()=>{let id=localStorage.getItem("eu_scout_session_id");if(!id){id=makeSessionId();localStorage.setItem("eu_scout_session_id",id)}setSessionId(id);try{const s=JSON.parse(localStorage.getItem("eu_scout_saved")||"[]");if(Array.isArray(s))setSaved(s.slice(0,20))}catch{}try{const h=JSON.parse(localStorage.getItem("eu_scout_chat")||"[]");if(Array.isArray(h))setChatMessages(h.slice(-40))}catch{}fetch("/api/health",{cache:"no-store"}).then(r=>r.json()).then(d=>setLive(Boolean(d?.integrations?.aliexpress))).catch(()=>setLive(false))},[]);
 useEffect(()=>{localStorage.setItem("eu_scout_saved",JSON.stringify(saved.slice(0,20)))},[saved]);useEffect(()=>{localStorage.setItem("eu_scout_chat",JSON.stringify(chatMessages.slice(-40)))},[chatMessages]);
 const visibleProducts=useMemo(()=>{const list=[...products];if(sort==="price")return list.sort((a,b)=>Number(a.price??Infinity)-Number(b.price??Infinity));if(sort==="rating")return list.sort((a,b)=>(feedback(b)??-1)-(feedback(a)??-1));if(sort==="sales")return list.sort((a,b)=>Number(b.sales??0)-Number(a.sales??0));return list.sort((a,b)=>Number(a.rank??999)-Number(b.rank??999))},[products,sort]);
 async function runSearch(message?:string,demandLabel?:string){if(loading)return;const text=(message??query).trim();if(!text&&!imageData){setError("Γράψε τι ψάχνεις ή διάλεξε μία ανάγκη.");return}setLoading(true);setError("");setClarification(null);if(demandLabel)setActiveDemand(demandLabel);try{const response=await fetch("/api/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:text,sessionId,...(imageData?{image:imageData}:{})})});const data=await response.json() as SearchResponse;if(!response.ok)throw new Error("search_failed");setUnderstood(data.understood||"");setResultQuery(data.query||text);if(data.status==="clarify"){setProducts([]);setClarification({question:data.question||"Χρειάζομαι μία μικρή διευκρίνιση.",options:data.options||[]})}else{setProducts(Array.isArray(data.products)?data.products:[]);setSort("recommended");requestAnimationFrame(()=>resultsRef.current?.scrollIntoView({behavior:"smooth",block:"start"}))}}catch{setProducts([]);setError("Η live αναζήτηση δεν απάντησε. Δοκίμασε ξανά — η επιλογή σου δεν χάθηκε.")}finally{setLoading(false)}}
 function searchDemand(family:DemandFamily,item:DemandItem){const message=composedQuery(item.query,grade,budget,priority,season);setQuery(message);void runSearch(message,`${family.title} · ${item.label}`)}
 function toggleSaved(p:Product){const id=p.productId||p.title;setSaved(c=>c.some(x=>(x.productId||x.title)===id)?c.filter(x=>(x.productId||x.title)!==id):[p,...c].slice(0,20))}
 function toggleCompare(p:Product){const id=p.productId||p.title;setCompare(c=>c.some(x=>(x.productId||x.title)===id)?c.filter(x=>(x.productId||x.title)!==id):c.length>=3?c:[...c,p])}
 function pickFile(file?:File){if(!file||!file.type.startsWith("image/"))return;if(file.size>8*1024*1024){setError("Η φωτογραφία είναι πολύ μεγάλη. Διάλεξε εικόνα έως 8 MB.");return}const reader=new FileReader();reader.onload=()=>{setImageData(String(reader.result||""));setImageName(file.name||"Φωτογραφία προϊόντος")};reader.readAsDataURL(file)}
 async function sendChat(override?:string){const message=(override??chatInput).trim();if(!message||chatting)return;setChatInput("");setSuggested([]);setChatMessages(c=>[...c,{role:"user",text:message}]);setChatting(true);try{const response=await fetch("/api/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message,sessionId})});const data=await response.json() as ChatResponse;if(!response.ok)throw new Error("chat_failed");setChatMessages(c=>[...c,{role:"assistant",text:data.reply||"Δοκίμασε να το πεις λίγο διαφορετικά.",products:(data.products||[]).slice(0,3)}]);setSuggested(data.suggestedReplies||[])}catch{setChatMessages(c=>[...c,{role:"assistant",text:"Δεν μπόρεσα να απαντήσω αυτή τη στιγμή. Δοκίμασε ξανά σε λίγο."}])}finally{setChatting(false)}}
 function resetChat(){const fresh=makeSessionId();localStorage.setItem("eu_scout_session_id",fresh);setSessionId(fresh);setChatMessages([]);setSuggested([])}
 const hero=season==="bts"?{badge:"BACK TO SCHOOL · ΕΩΣ 30/09",title:"Λιγότερο ψάξιμο. Πιο γρήγορα έτοιμοι για σχολείο.",lede:"Διάλεξε τάξη, budget και μία ανάγκη. Το EU Scout μετατρέπει την επιλογή σου σε σωστή live αναζήτηση και κρατά μόνο σχετικά προϊόντα."}:{badge:"EU SCOUT · SMART SHOPPING",title:"Βρες αυτό που χρειάζεσαι χωρίς ατελείωτο scrolling.",lede:"Γράψε τι θέλεις με φυσικό τρόπο ή ξεκίνα από μία οικογένεια αναγκών. Το Smart Search μετατρέπει το κείμενο σε σωστό query και φιλτράρει τα άσχετα."};
 return <>
  <header className="site-header"><div className="header-inner"><div className="brand-lockup"><div className="brand-mark">EU</div><div><strong>EU Scout</strong><span>smart product finder</span></div></div><div className="tool-switch"><span className="tool-active">⌕ Έξυπνη Αναζήτηση</span><button type="button" onClick={()=>setChatOpen(true)}>✦ AI Σύμβουλος</button></div><div className="header-actions"><div className="live-chip"><i className={live?"live":""}/>{live?"Live προϊόντα":"Έλεγχος"}</div><button className="saved-button" type="button" onClick={()=>saved.length&&setCompareOpen(true)}>♡ <span>{saved.length} αποθηκευμένα</span></button></div></div></header>
  <main>
   <section className={`hero ${season}`}><div className="hero-copy"><div className="campaign-label"><span>{hero.badge}</span><b>{season==="bts"?"για γονείς που θέλουν να τελειώνουν χωρίς άγχος":"γενική αναζήτηση για κάθε κατηγορία"}</b></div><h1>{hero.title}</h1><p>{hero.lede}</p><div className="promise-row"><span>✓ semantic query</span><span>✓ budget ως όριο</span><span>✓ σχετικό προϊόν, όχι parts</span></div></div><div className={`season-placeholder ${season}`} aria-hidden="true"><div className="placeholder-top"><span>{season==="bts"?"SCHOOL KIT":"SMART FINDS"}</span><b>{season==="bts"?"01 → 09":"ALL YEAR"}</b></div><div className="placeholder-stage"><i/><i/><i/><span>{season==="bts"?"🎒":"⌕"}</span></div><div className="placeholder-caption">{season==="bts"?"Θεματικό visual placeholder — θα αντικαθίσταται ανά campaign":"Dynamic seasonal visual placeholder"}</div></div></section>
   <section className="quick-config"><div className="config-title"><span>ΓΡΗΓΟΡΗ ΡΥΘΜΙΣΗ</span><b>{season==="bts"?"Δώσε 3 στοιχεία μία φορά":"Προαιρετικά φίλτρα πριν ξεκινήσεις"}</b></div>{season==="bts"&&<label>Τάξη<select value={grade} onChange={e=>setGrade(e.target.value)}>{gradeOptions.map(x=><option key={x}>{x}</option>)}</select></label>}<label>Όριο ανά προϊόν<div className="budget-inline"><span>€</span><input inputMode="numeric" value={budget} placeholder="π.χ. 45" onChange={e=>setBudget(e.target.value.replace(/[^0-9]/g,""))}/></div></label><div className="priority-inline"><span>Προτεραιότητα</span><div><button className={priority==="value"?"active":""} onClick={()=>setPriority("value")}>Τιμή</button><button className={priority==="balanced"?"active":""} onClick={()=>setPriority("balanced")}>Ισορροπία</button><button className={priority==="fast"?"active":""} onClick={()=>setPriority("fast")}>Ταχύτητα</button></div></div></section>
   <section className="demand-section"><div className="section-heading"><div><span>01 / DEMAND FAMILIES</span><h2>{season==="bts"?"Κλείσε μία ανάγκη κάθε φορά.":"Ξεκίνα από αυτό που θέλεις να πετύχεις."}</h2></div><p>Κάθε οικογένεια περιέχει συγγενικές ανάγκες. Επιλέγεις μία και η αναζήτηση ξεκινά ήδη με τα σωστά συμφραζόμενα.</p></div><div className="demand-grid">{demands.map(f=><article className="demand-card" key={f.id}><div className={`demand-art ${f.className}`}><span className="demand-icon">{f.icon}</span><i/><i/><i/></div><div className="demand-body"><span>{f.eyebrow}</span><h3>{f.title}</h3><p>{f.note}</p><div className="demand-items">{f.items.map(item=><button type="button" key={item.label} onClick={()=>searchDemand(f,item)}>{item.label}<b>→</b></button>)}</div></div></article>)}</div></section>
   <section className="direct-search"><div className="direct-copy"><span>02 / SMART SEARCH AGENT</span><h2>Ψάχνεις κάτι άλλο; Γράψ’ το φυσικά.</h2><p>Δεν χρειάζεται ειδικό prompt. «Ρομποτική σκούπα για τρίχες σκύλου μέχρι 250€» ή «μαύρη τσάντα για Β΄ Γυμνασίου μέχρι 45€».</p><div className="agent-separation"><b>⌕ Smart Search</b><span>Καταλαβαίνει intent → φτιάχνει query → βρίσκει προϊόντα.</span><b>✦ AI Σύμβουλος</b><span>Συζητά, θυμάται και σε βοηθά να διαλέξεις.</span></div></div><div><div className="search-box"><textarea value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void runSearch()}}} placeholder="Τι ψάχνεις; Γράψε προϊόν, χρήση, budget ή χαρακτηριστικά…" rows={3}/><div className="search-controls"><button className="photo-cta" type="button" onClick={()=>fileRef.current?.click()}>▣ Φωτογραφία</button><button className="main-cta" type="button" disabled={loading} onClick={()=>void runSearch()}>{loading?"Ψάχνω…":"Έξυπνη αναζήτηση"}<span>→</span></button><input ref={fileRef} hidden type="file" accept="image/*" capture="environment" onChange={e=>pickFile(e.target.files?.[0])}/></div>{imageData&&<div className="image-ready"><img src={imageData} alt="Προεπισκόπηση"/><div><b>Φωτογραφία έτοιμη</b><span>{imageName}</span></div><button type="button" onClick={()=>{setImageData(null);setImageName("")}}>Αφαίρεση</button></div>}</div>{error&&<div className="inline-message error">{error}</div>}{clarification&&<div className="inline-message"><b>{clarification.question}</b><div>{clarification.options.map(o=><button key={o} type="button" onClick={()=>{const next=`${query} ${o}`.trim();setQuery(next);void runSearch(next)}}>{o}</button>)}</div></div>}</div></section>
   <section ref={resultsRef} className={`results-section ${loading||products.length||resultQuery||clarification?"visible":""}`} aria-live="polite">{loading?<div className="skeleton-grid"><div/><div/><div/></div>:products.length?<><div className="results-head"><div><span>{activeDemand?`DEMAND · ${activeDemand}`:"SEMANTIC SEARCH RESULT"}</span><h2>{understood||"Οι πιο σχετικές επιλογές"}</h2><div className="query-translation"><b>Έψαξα ως</b><code>{resultQuery}</code></div></div><label>Ταξινόμηση<select value={sort} onChange={e=>setSort(e.target.value as SortKey)}><option value="recommended">Προτεινόμενα</option><option value="price">Χαμηλότερη τιμή</option><option value="rating">Υψηλότερη αξιολόγηση</option><option value="sales">Περισσότερες πωλήσεις</option></select></label></div><div className="product-grid">{visibleProducts.map((p,index)=>{const href=safeUrl(p.promotionLink)||safeUrl(p.productUrl),id=p.productId||p.title||String(index),isSaved=saved.some(x=>(x.productId||x.title)===id),isCompared=compare.some(x=>(x.productId||x.title)===id),rating=feedback(p);return <article className="product-card" key={id}><div className="product-image-wrap"><img src={safeUrl(p.imageUrl)||"data:image/svg+xml;charset=UTF-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='600' height='480'%3E%3Crect width='100%25' height='100%25' fill='%23eef1ee'/%3E%3C/svg%3E"} alt={p.title||"Προϊόν"}/><span className="role-badge">{productRole(p,products)}</span></div><div className="product-card-body"><h3>{p.title||"Προϊόν"}</h3><div className="price-line"><strong>{money(p.price,p.currency)||"—"}</strong>{Number.isFinite(Number(p.originalPrice))&&Number(p.originalPrice)>Number(p.price)?<del>{money(p.originalPrice,p.currency)}</del>:null}</div>{p.why&&<p className="why"><b>Γιατί ταιριάζει:</b> {p.why}</p>}<div className="evidence-row">{rating!==null&&<span>★ {rating}%</span>}{Number(p.sales)>0&&<span>{Number(p.sales).toLocaleString("el-GR")} πωλήσεις</span>}{p.verification?.euWarehouse==="verified"&&<span className="verified">EU warehouse ✓</span>}{p.verification?.freeShipping==="verified"&&<span className="verified">Δωρεάν μεταφορικά ✓</span>}</div><div className="card-actions">{href?<a href={href} target="_blank" rel="sponsored noopener noreferrer">Δες το προϊόν <span>↗</span></a>:<span className="no-link">Link μη διαθέσιμο</span>}<button className={isSaved?"active":""} onClick={()=>toggleSaved(p)}>♡</button><button className={isCompared?"active":""} disabled={!isCompared&&compare.length>=3} onClick={()=>toggleCompare(p)}>⇄</button></div></div></article>})}</div></>:resultQuery&&!clarification?<div className="no-results"><div><span>ΚΑΜΙΑ ΑΣΦΑΛΗΣ ΕΠΙΛΟΓΗ</span><h2>Δεν θα γεμίσουμε τη σελίδα με άσχετα προϊόντα.</h2><p>Άλλαξε λίγο το κείμενο ή χαλάρωσε έναν περιορισμό.</p></div><button type="button" onClick={()=>{setQuery("");setResultQuery("");setActiveDemand("");window.scrollTo({top:0,behavior:"smooth"})}}>Νέα αναζήτηση</button></div>:null}</section>
   <footer><div><strong>EU Scout</strong><span>Smart Search + ξεχωριστός AI Σύμβουλος.</span></div><p>Live δεδομένα όταν διατίθενται. Δεν επινοούμε stock, warehouse, μεταφορικά ή αξιολογήσεις. Ορισμένα εξωτερικά links μπορεί να είναι affiliate links.</p></footer>
  </main>
  {compare.length>=2&&<button className="compare-fab" onClick={()=>setCompareOpen(true)}>Σύγκρινε {compare.length}</button>}<button className="chat-fab" onClick={()=>setChatOpen(v=>!v)}><span>✦</span><b>AI Σύμβουλος</b></button>
  {chatOpen&&<aside className="chat-panel"><div className="chat-head"><div><b>AI Σύμβουλος Αγορών</b><span>Συζήτηση, μνήμη και βοήθεια επιλογής — ανεξάρτητο από το Smart Search.</span></div><div><button onClick={resetChat}>Νέα</button><button onClick={()=>setChatOpen(false)}>×</button></div></div><div className="chat-log">{chatMessages.length===0&&<div className="chat-intro"><b>Πες μου τι θέλεις να αποφασίσεις.</b><span>Μπορώ να συγκρίνω επιλογές, να θυμάμαι τα κριτήριά σου και να ζητήσω live προϊόντα όταν χρειάζεται.</span></div>}{chatMessages.map((m,i)=><div className={`bubble ${m.role}`} key={`${m.role}-${i}`}><span>{m.text}</span>{m.products?.length?<div className="mini-products vertical">{m.products.map((p,j)=>{const href=safeUrl(p.promotionLink)||safeUrl(p.productUrl);return href?<a href={href} target="_blank" rel="sponsored noopener noreferrer" key={p.productId||j}><div className="mini-image"><img src={safeUrl(p.imageUrl)||""} alt=""/></div><div className="mini-content"><b>{p.title}</b><strong>{money(p.price,p.currency)}</strong><span>Δες το προϊόν ↗</span></div></a>:null})}</div>:null}</div>)}{chatting&&<div className="typing">Σκέφτομαι…</div>}</div>{suggested.length>0&&<div className="suggested">{suggested.slice(0,4).map(x=><button key={x} onClick={()=>void sendChat(x)}>{x}</button>)}</div>}<div className="chat-compose"><textarea value={chatInput} onChange={e=>setChatInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void sendChat()}}} placeholder="Ρώτησε, σύγκρινε ή συνέχισε από πριν…" rows={2}/><button disabled={chatting} onClick={()=>void sendChat()}>→</button></div></aside>}
  {compareOpen&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setCompareOpen(false)}}><section className="compare-modal"><div className="compare-head"><div><span>ΓΡΗΓΟΡΗ ΣΥΓΚΡΙΣΗ</span><h2>{compare.length?`${compare.length} επιλογές δίπλα-δίπλα`:`${saved.length} αποθηκευμένα`}</h2></div><button onClick={()=>setCompareOpen(false)}>×</button></div><div className="compare-grid">{(compare.length?compare:saved.slice(0,3)).map((p,i)=><article key={p.productId||i}><img src={safeUrl(p.imageUrl)||""} alt=""/><h3>{p.title}</h3><strong>{money(p.price,p.currency)}</strong><dl><div><dt>Αξιολόγηση</dt><dd>{feedback(p)!==null?`${feedback(p)}%`:"Δεν δίνεται"}</dd></div><div><dt>Πωλήσεις</dt><dd>{Number(p.sales)>0?Number(p.sales).toLocaleString("el-GR"):"Δεν δίνονται"}</dd></div><div><dt>EU warehouse</dt><dd>{p.verification?.euWarehouse==="verified"?"Επιβεβαιωμένο":"Δεν επιβεβαιώνεται"}</dd></div></dl></article>)}</div></section></div>}
 </>
}
