"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import type { Product, SearchResponse } from "@/lib/types";
import { homeDemandCases, suggestDemandCases, type DemandCase } from "@/lib/demand";

const premiumIdeas = [
  { title: "Ρομποτική σκούπα & σφουγγάρισμα", query: "premium robot vacuum mop self empty pet hair over 100 euro", role: "Top Match", icon: "◉" },
  { title: "Εργονομική καρέκλα γραφείου", query: "premium ergonomic office chair adjustable lumbar over 100 euro", role: "Best Value", icon: "▤" },
  { title: "4K Smart Projector", query: "premium 4k smart projector home cinema over 100 euro", role: "High Demand", icon: "◈" },
];

function safeHref(product?: Product) { const value=product?.promotionLink||product?.productUrl;if(!value)return null;try{const url=new URL(value);return url.protocol==="https:"||url.protocol==="http:"?url.href:null}catch{return null} }
function eur(value?:number,currency="EUR"){if(!Number.isFinite(Number(value)))return null;try{return new Intl.NumberFormat("el-GR",{style:"currency",currency,maximumFractionDigits:2}).format(Number(value))}catch{return`${Number(value).toFixed(2)} ${currency}`}}
function makeSession(){if(typeof crypto!=="undefined"&&"randomUUID" in crypto)return crypto.randomUUID();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,(c)=>{const r=Math.random()*16|0,v=c==="x"?r:(r&3|8);return v.toString(16)})}

export function V4Home(){
 const[query,setQuery]=useState("");const[sessionId,setSessionId]=useState("");const[loading,setLoading]=useState(false);const[response,setResponse]=useState<SearchResponse|null>(null);const[error,setError]=useState("");const[activeDemand,setActiveDemand]=useState<string|null>(null);const[searchFocused,setSearchFocused]=useState(false);const searchRef=useRef<HTMLInputElement>(null);
 async function runSearch(raw:string){const cleaned=raw.trim();if(!cleaned||loading)return;setLoading(true);setError("");setResponse(null);try{const message=`${cleaned}. Μόνο προϊόντα με επιβεβαιωμένη αποστολή από αποθήκη ΕΕ προς Ελλάδα.`;const request=await fetch("/api/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message,sessionId})});const data=await request.json() as SearchResponse&{error?:string};if(!request.ok)throw new Error(data.error||"Η αναζήτηση δεν ολοκληρώθηκε.");setResponse(data);window.setTimeout(()=>document.querySelector("#results")?.scrollIntoView({behavior:"smooth",block:"start"}),50)}catch(cause){setError(cause instanceof Error?cause.message:"Κάτι πήγε στραβά.")}finally{setLoading(false)}}
 useEffect(()=>{const key="vresmou-session",existing=window.localStorage.getItem(key),id=existing||makeSession();window.localStorage.setItem(key,id);setSessionId(id);const params=new URLSearchParams(window.location.search),initial=params.get("q");if(initial){setQuery(initial);window.setTimeout(()=>void runSearch(initial),80)}},[]);
 const topProducts=useMemo(()=>(response?.products||[]).slice(0,6),[response]);const demands=useMemo(()=>homeDemandCases(6),[]);const semanticSuggestions=useMemo(()=>suggestDemandCases(query,5),[query]);
 function submit(event:FormEvent){event.preventDefault();void runSearch(query)}
 function chooseDemand(item:DemandCase){setActiveDemand(item.slug);setQuery(item.searchQuery);setSearchFocused(false);void runSearch(item.searchQuery)}
 async function share(kind:string){const url=window.location.href,text=`Βρήκα μια AI έρευνα αγορών στο ΒρεςΜου: ${query||"έξυπνες λύσεις από EU αποθήκες"}`,encodedUrl=encodeURIComponent(url),encodedText=encodeURIComponent(text),links:Record<string,string>={facebook:`https://www.facebook.com/sharer/sharer.php?u=${encodedUrl}`,messenger:`fb-messenger://share/?link=${encodedUrl}`,whatsapp:`https://wa.me/?text=${encodedText}%20${encodedUrl}`,viber:`viber://forward?text=${encodedText}%20${encodedUrl}`,pinterest:`https://www.pinterest.com/pin/create/button/?url=${encodedUrl}&description=${encodedText}`};if(kind==="native"||kind==="instagram"||kind==="tiktok"){if(navigator.share){await navigator.share({title:"ΒρεςΜου",text,url});return}await navigator.clipboard?.writeText(`${text} ${url}`);window.alert("Ο σύνδεσμος αντιγράφηκε. Μπορείς να τον μοιραστείς στην εφαρμογή σου.");return}const target=links[kind];if(target)window.open(target,"_blank","noopener,noreferrer")}
 return <main className="v4-shell">
  <header className="v4-header"><a href="#top" className="brand" aria-label="ΒρεςΜου αρχική"><span className="brand-mark">◒</span><span><b>ΒρεςΜου</b><small>AI αγορές με νόημα</small></span></a><nav aria-label="Κύρια πλοήγηση"><a href="/methodology">Πώς δουλεύει</a><a href="/premium">Premium 100€+</a><a href="/needs">Ανάγκες</a><button type="button" onClick={()=>{searchRef.current?.focus();searchRef.current?.scrollIntoView({behavior:"smooth",block:"center"})}}>AI Advisor</button><a href="#trust">Για επιχειρήσεις</a><a className="nav-offer" href="#offer">Προσφορές</a></nav><div className="header-actions"><button type="button" aria-label="Αποθηκευμένα">♡</button><button type="button" className="login-button">Σύνδεση</button><button type="button" className="ai-button" onClick={()=>searchRef.current?.focus()}>✦ AI αναζήτηση</button></div></header>
  <aside className="share-rail" aria-label="Κοινοποίηση"><span>Κοινοποίηση</span><button onClick={()=>void share("facebook")} aria-label="Facebook">f</button><button onClick={()=>void share("messenger")} aria-label="Messenger">m</button><button onClick={()=>void share("whatsapp")} aria-label="WhatsApp">w</button><button onClick={()=>void share("viber")} aria-label="Viber">v</button><button onClick={()=>void share("tiktok")} aria-label="TikTok">♪</button><button onClick={()=>void share("instagram")} aria-label="Instagram">◎</button><button onClick={()=>void share("pinterest")} aria-label="Pinterest">p</button><button onClick={()=>void share("native")} aria-label="Άλλες εφαρμογές">↗</button></aside>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">AI DEMAND INTELLIGENCE · EU ONLY</p><h1>Τι θέλεις να βρεις <span>σήμερα;</span></h1><p className="hero-lead">Το AI καταλαβαίνει την ανάγκη, αναλύει demand & pain gaps και ξεχωρίζει λύσεις από ευρωπαϊκές αποθήκες — χωρίς άσχετα αποτελέσματα.</p><form className="hero-search" onSubmit={submit}><span className="search-glyph">⌕</span><input ref={searchRef} value={query} onChange={(e)=>setQuery(e.target.value)} onFocus={()=>setSearchFocused(true)} onBlur={()=>window.setTimeout(()=>setSearchFocused(false),120)} placeholder="Γράψε τι χρειάζεσαι ή τι θέλεις να πετύχεις..." aria-label="AI semantic αναζήτηση"/><button type="button" className="icon-action" onClick={()=>window.alert("Η αναζήτηση με φωτογραφία θα χρησιμοποιήσει το υπάρχον AliExpress image-search όταν υπάρχει ενεργό credential.")}>▣</button><button type="submit" className="search-submit" disabled={loading}>{loading?"Αναλύω...":"Βρες μου λύση ✦"}</button></form>
  {searchFocused&&semanticSuggestions.length>0&&<div className="semantic-suggestions" role="listbox" aria-label="Semantic προτάσεις"><div className="suggestion-label">✦ Κατάλαβα πιθανές ανάγκες</div>{semanticSuggestions.map(({item,score})=><button key={item.slug} type="button" role="option" aria-selected={false} onMouseDown={(e)=>e.preventDefault()} onClick={()=>{setQuery(item.searchQuery);setSearchFocused(false);void runSearch(item.searchQuery)}}><span className="suggestion-icon">{item.icon}</span><span><b>{item.title}</b><small>{item.subtitle}</small></span><em>{score}%</em></button>)}<a href="/needs">Δες όλες τις ανάγκες →</a></div>}
  <div className="capability-row" aria-label="Δυνατότητες"><span>● Demand Analysis</span><span>● Pain-Gap AI</span><span>● Semantic Search</span><span>● RAG Matching</span><span className="eu-chip">🇪🇺 EU αποθήκες μόνο</span></div></div><div className="hero-visual" aria-label="AI buying intelligence visual"><span className="eu-switch">🇪🇺 EU αποθήκες μόνο <i>●</i></span><div className="neural-orb">✦<small>AI</small></div><button type="button" className="floating-product fp-one" onClick={()=>void runSearch("premium robot vacuum pet hair self empty")}>◉</button><button type="button" className="floating-product fp-two" onClick={()=>void runSearch("premium 4k smart projector home cinema")}>◈</button><button type="button" className="floating-product fp-three" onClick={()=>void runSearch("premium ergonomic office chair lumbar support")}>▤</button><div className="visual-copy"><b>Από το pain στη σωστή αγορά.</b><span>Το AI ελέγχει συνάφεια, budget, evidence και EU fulfilment.</span></div></div></section>
  <section className="needs" id="needs"><div className="section-heading"><div><p className="eyebrow">DEMAND → PAIN → SOLUTION</p><h2>Διάλεξε την ανάγκη σου — το AI αναλαμβάνει</h2></div><span>Κάθε κάρτα ξεκινά semantic έρευνα, όχι απλή κατηγορία.</span></div><div className="demand-grid">{demands.map((item)=><button key={item.slug} type="button" className={`demand-card ${activeDemand===item.slug?"active":""}`} onClick={()=>chooseDemand(item)}><span className="demand-icon">{item.icon}</span><b>{item.title}</b><p>{item.subtitle}</p><small>↗ {item.signalLabel}</small></button>)}</div><div className="section-link-row"><a href="/needs">Εξερεύνησε όλα τα pain cases →</a></div></section>
  <section className="premium" id="premium"><div className="section-heading"><div><p className="eyebrow">HIGH-VALUE DECISIONS</p><h2>Premium λύσεις 100€+</h2></div><span>Η λάθος μεγάλη αγορά κοστίζει περισσότερο. Ξεκίνα με AI έρευνα.</span></div><div className="premium-grid">{premiumIdeas.map((item)=><article className="premium-card" key={item.title}><div className="premium-art"><span>{item.icon}</span></div><div className="premium-body"><small>{item.role}</small><h3>{item.title}</h3><ul><li>EU warehouse gate</li><li>AI relevance & identity validation</li><li>Full disclosure πριν το click</li></ul><button type="button" onClick={()=>{setQuery(item.query);void runSearch(item.query)}}>Δες λύσεις →</button></div></article>)}</div></section>
  <section id="results" className={`results ${response||loading||error?"visible":""}`} aria-live="polite">{loading&&<div className="research-progress"><b>Το AI κάνει την έρευνα…</b><div className="progress-steps"><span>Καταλαβαίνω το intent</span><span>Ψάχνω live προϊόντα</span><span>Απορρίπτω άσχετα</span><span>Συγκρίνω</span></div></div>}{error&&<div className="error-box">{error}</div>}{response&&<><div className="result-summary"><p className="eyebrow">AI RESEARCH RESULT</p><h2>{response.understood||"Βρήκα αυτές τις επιλογές"}</h2>{response.warnings?.map((w)=><p className="warning" key={w}>⚠ {w}</p>)}{response.status==="clarify"&&response.question&&<div className="clarify"><b>{response.question}</b><div>{response.options?.map((option)=><button key={option} type="button" onClick={()=>{setQuery(`${query} ${option}`);void runSearch(`${query} ${option}`)}}>{option}</button>)}</div></div>}</div>{topProducts.length>0?<div className="result-grid">{topProducts.map((product,index)=>{const href=safeHref(product);return <article className="result-card" key={product.productId||`${product.title}-${index}`}><div className="result-image">{product.imageUrl?<img src={product.imageUrl} alt={product.title||"Προϊόν"}/>:<span>◫</span>}<b>{index===0?"AI TOP MATCH":index===1?"BEST VALUE":`#${index+1}`}</b></div><div className="result-body"><h3>{product.title||"Live προϊόν"}</h3><p className="price">{eur(product.price,product.currency)||"Τιμή στο AliExpress"}</p><p>{product.why||"Σχετικό live αποτέλεσμα από την AI έρευνα."}</p><div className="score-row"><span>AI Match</span><b>{product.matchScore!=null?`${product.matchScore}/100`:"—"}</b></div><div className="evidence-row"><span>EU stock: {product.verification?.euWarehouse||"unknown"}</span><span>Feedback: {product.verification?.positiveFeedback??"—"}</span></div>{href?<a href={href} target="_blank" rel="sponsored noopener noreferrer">Δες την τρέχουσα προσφορά →</a>:<button type="button" disabled>Δεν υπάρχει ασφαλής σύνδεσμος</button>}<small className="disclosure">Affiliate link · μπορεί να λάβουμε προμήθεια χωρίς επιπλέον κόστος για εσένα.</small></div></article>})}</div>:response.status==="complete"?<div className="empty-state"><b>Δεν θα σου δείξω άσχετα προϊόντα.</b><p>Δοκίμασε διαφορετική περιγραφή της ανάγκης ή επίλεξε μία σχετική pain λύση παραπάνω.</p></div>:null}</>}</section>
  <section className="method" id="how"><div className="section-heading"><div><p className="eyebrow">TRANSPARENT BY DESIGN</p><h2>Πώς βρίσκουμε τις ανάγκες και τις λύσεις</h2></div></div><div className="method-flow"><span><b>1</b> Demand signals<small>Market & internal intent</small></span><i>→</i><span><b>2</b> Pain-gap analysis<small>Πρόβλημα πριν το προϊόν</small></span><i>→</i><span><b>3</b> Semantic RAG<small>Greek / Greeklish / context</small></span><i>→</i><span><b>4</b> AliExpress live<small>EU warehouse requirement</small></span><i>→</i><span><b>5</b> AI validation<small>Relevance, evidence, value</small></span></div></section>
  <section className="trust-strip" id="trust"><span><b>✓ Επαληθεύσιμες πληροφορίες</b><small>Δεν γεμίζουμε κενά με εικασίες</small></span><span><b>✓ Πλήρης διαφάνεια</b><small>Τι ξέρουμε και τι όχι</small></span><span><b>✓ EU fulfilment focus</b><small>Για γρηγορότερη και ασφαλέστερη αγορά</small></span><span><b>✓ Affiliate disclosure</b><small>Η προμήθεια δεν αλλάζει το relevance score</small></span></section>
  <section className="offer-box" id="offer"><div><p className="eyebrow">FREE BUYING BRIEF</p><h2>Κράτησε την έρευνα και τις καλύτερες επιλογές.</h2><p>Το personalized PDF/QR funnel ενεργοποιείται στο επόμενο implementation stage.</p></div><button type="button" onClick={()=>window.alert("Stage 4: email + PDF + QR funnel")}>Θέλω τον AI οδηγό →</button></section>
  <footer className="v4-footer"><span><b>🇪🇺 EU-first</b><small>Warehouse validation</small></span><span><b>✦ Semantic AI</b><small>Intent before keywords</small></span><span><b>◎ Transparent</b><small>Evidence & unknowns</small></span><span><b>24/7</b><small>AI discovery</small></span><button type="button" onClick={()=>{searchRef.current?.focus();window.scrollTo({top:0,behavior:"smooth"})}}>Ξεκίνα τώρα →</button></footer>
 </main>
}
