export type DemandCase = {
  slug: string;
  world: "home" | "pets" | "car" | "student" | "office" | "family" | "tech" | "energy";
  icon: string;
  title: string;
  subtitle: string;
  searchQuery: string;
  aliases: string[];
  solutionPaths: string[];
  premium: boolean;
  homePriority: number;
  signalLabel: string;
};

export const DEMAND_CASES: DemandCase[] = [
  {slug:"pet-hair-home",world:"pets",icon:"●",title:"Τρίχες κατοικιδίου στο σπίτι",subtitle:"Καναπές, χαλιά, δάπεδα και καθημερινός καθαρισμός χωρίς άσχετα αξεσουάρ.",searchQuery:"best solution for pet hair across home robot vacuum cordless vacuum pet hair",aliases:["τρίχες σκύλου παντού","τριχες σκυλου","τρίχες γάτας","τριχες γατας","pet hair home","dog hair everywhere","cat hair sofa","trixes skylou","trixes gatas"],solutionPaths:["Αυτόματος καθημερινός καθαρισμός","Βαθύς καθαρισμός","Καναπές & υφάσματα","Αυτοκίνητο"],premium:true,homePriority:100,signalLabel:"Pain-gap"},
  {slug:"bedroom-heat-no-ac",world:"home",icon:"☀",title:"Ζέστη στο υπνοδωμάτιο",subtitle:"Δροσιά για ύπνο χωρίς μόνιμη εγκατάσταση ή air condition.",searchQuery:"quiet bedroom cooling fan portable cooling renter no installation",aliases:["ζέστη στο υπνοδωμάτιο","καύσωνας δωμάτιο","δεν έχω air condition","δροσια χωρις κλιματιστικο","zesti sto domatio","room too hot at night","quiet fan sleep"],solutionPaths:["Ήσυχη κυκλοφορία αέρα","Μείωση ηλιακού φορτίου","Portable cooling","Night comfort"],premium:false,homePriority:98,signalLabel:"Seasonal"},
  {slug:"small-home-storage",world:"home",icon:"⌂",title:"Μικρός χώρος, περισσότερη τάξη",subtitle:"Storage και πολυχρηστικές λύσεις για μικρά ελληνικά σπίτια.",searchQuery:"small apartment space saving storage organization multifunction furniture",aliases:["δεν χωράνε τα πράγματα","μικρο σπιτι οργανωση","μικρός χώρος","small apartment storage","space saving home","organosi mikrou spitiou"],solutionPaths:["Κάθετο storage","Κρυφή αποθήκευση","Καλώδια & μικροαντικείμενα","Πολυχρηστικές λύσεις"],premium:false,homePriority:93,signalLabel:"Υψηλό ενδιαφέρον"},
  {slug:"wifi-dead-zone",world:"tech",icon:"⌁",title:"Το Wi‑Fi δεν πιάνει καλά",subtitle:"Λύσεις για dead zones, υπνοδωμάτια και μεγαλύτερα σπίτια.",searchQuery:"mesh wifi system wifi 6 extender dead zone large home",aliases:["δεν πιάνει wifi","wifi στο υπνοδωμάτιο","χαμηλό σήμα wifi","wifi dead zone","wifi den pianei","mesh wifi σπίτι","internet signal bedroom"],solutionPaths:["Mesh Wi‑Fi","Wi‑Fi extender","Καλύτερη τοποθέτηση router","Ethernet bridge"],premium:true,homePriority:91,signalLabel:"Pain-gap"},
  {slug:"ergonomic-home-office",world:"office",icon:"▣",title:"Home Office χωρίς πόνους",subtitle:"Εργονομία, φωτισμός και setup για πολλές ώρες εργασίας.",searchQuery:"premium ergonomic home office chair lumbar monitor arm desk lighting",aliases:["πονάει η μέση στο γραφείο","καρέκλα για πολλές ώρες","εργονομικο home office","ergonomic office","back pain desk","karekla grafeiou mesi","home office comfort"],solutionPaths:["Εργονομική καρέκλα","Monitor positioning","Foot support","Task lighting"],premium:true,homePriority:96,signalLabel:"Υψηλό ενδιαφέρον"},
  {slug:"student-smart-setup",world:"student",icon:"✦",title:"Φοιτητικό setup με σωστό budget",subtitle:"Διάβασμα, τεχνολογία και οργάνωση χωρίς περιττά gadgets.",searchQuery:"student desk setup laptop accessories study productivity small room",aliases:["φοιτητικό σπίτι","setup φοιτητή","φοιτητικο γραφειο","student setup","foititiko spiti","διάβασμα μικρό δωμάτιο","study setup"],solutionPaths:["Study desk","Lighting","Laptop ergonomics","Organization"],premium:true,homePriority:90,signalLabel:"Seasonal"},
  {slug:"car-summer-comfort",world:"car",icon:"◆",title:"Αυτοκίνητο το καλοκαίρι",subtitle:"Ζέστη, οργάνωση, φόρτιση και άνεση στις μετακινήσεις.",searchQuery:"car summer heat protection organization premium car accessories charging",aliases:["ζέστη στο αυτοκίνητο","αυτοκινητο καλοκαιρι","car summer heat","car organization","zesti sto autokinito","σκίαστρο αυτοκινήτου","car travel comfort"],solutionPaths:["Sun protection","Car organization","Fast charging","Travel comfort"],premium:false,homePriority:94,signalLabel:"Seasonal"},
  {slug:"elderly-home-safety",world:"family",icon:"◎",title:"Ασφάλεια για γονείς στο σπίτι",subtitle:"Φωτισμός, ειδοποιήσεις και πρακτικές λύσεις καθημερινής ασφάλειας.",searchQuery:"elderly home safety smart sensor lighting alert easy use",aliases:["ασφάλεια ηλικιωμένου","γονείς μόνοι σπίτι","elderly safety home","senior home safety","goneis asfaleia","νυχτερινός φωτισμός γονείς"],solutionPaths:["Motion lighting","Door alerts","Simple smart buttons","Bathroom safety aids"],premium:false,homePriority:89,signalLabel:"Pain-gap"},
  {slug:"home-humidity",world:"home",icon:"◌",title:"Υγρασία και μούχλα",subtitle:"Μπάνιο, ντουλάπα και δωμάτια με συμπύκνωση ή μυρωδιά υγρασίας.",searchQuery:"home humidity dehumidifier moisture bathroom wardrobe hygrometer",aliases:["υγρασία στο μπάνιο","μουχλα τοιχο","μυρωδιά υγρασίας","humidity bathroom","moisture bedroom","ygrasia mpanio","moula spiti"],solutionPaths:["Measure humidity","Dehumidification","Wardrobe moisture","Air circulation"],premium:true,homePriority:95,signalLabel:"Pain-gap"},
  {slug:"home-cinema-projector",world:"tech",icon:"◈",title:"Home cinema χωρίς τηλεόραση",subtitle:"Projector, ήχος και σωστή φωτεινότητα με βάση τον χώρο.",searchQuery:"premium 4k smart projector home cinema high brightness auto focus",aliases:["projector για σαλόνι","home cinema projector","4k projector","προτζεκτορας σπιτι","projector living room","protzektoras"],solutionPaths:["4K projector","Screen / wall setup","Audio","Ambient light"],premium:true,homePriority:82,signalLabel:"Premium"},
  {slug:"power-backup-home",world:"energy",icon:"ϟ",title:"Ρεύμα & backup στο σπίτι",subtitle:"Power stations και εφεδρική τροφοδοσία για διακοπές ρεύματος και εξοχικό.",searchQuery:"portable power station home backup lifepo4 1000w 2000w EU",aliases:["power station σπίτι","διακοπή ρεύματος backup","μπαταρια σπιτι","portable power station","ρεύμα εξοχικό","power backup home"],solutionPaths:["Portable power station","Solar input","UPS-like backup","Camping / εξοχικό"],premium:true,homePriority:85,signalLabel:"Premium"},
  {slug:"smart-cleaning-premium",world:"home",icon:"◉",title:"Αυτόματος καθαρισμός premium",subtitle:"Robot vacuums υψηλής αξίας με dock, mop και σωστό fit για το σπίτι.",searchQuery:"premium robot vacuum mop self empty auto wash station lidar pet hair",aliases:["ρομποτική σκούπα premium","robot vacuum self empty","ρομποτ σκουπα σφουγγαρισμα","robot mop dock","rompot skoupa premium"],solutionPaths:["Self-empty","Auto wash mop","Pet hair","Navigation"],premium:true,homePriority:88,signalLabel:"Premium 100€+"}
];

export function normalizeDemandText(input: string) {
  return input.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/ς/g, "σ").replace(/[^a-z0-9α-ω]+/g, " ").replace(/\s+/g, " ").trim();
}
function tokens(input: string) { return normalizeDemandText(input).split(" ").filter((item) => item.length > 1); }
function trigrams(input: string) { const text=` ${normalizeDemandText(input)} `,out=new Set<string>();for(let i=0;i<=text.length-3;i++)out.add(text.slice(i,i+3));return out; }
function similarity(a:string,b:string){const aa=trigrams(a),bb=trigrams(b);if(!aa.size||!bb.size)return 0;let shared=0;aa.forEach((v)=>{if(bb.has(v))shared+=1});return(2*shared)/(aa.size+bb.size)}
export function scoreDemandCase(input:string,item:DemandCase){const q=normalizeDemandText(input);if(!q)return 0;const qTokens=tokens(q),fields=[item.title,item.subtitle,item.searchQuery,...item.aliases,...item.solutionPaths];let best=0;for(const field of fields){const f=normalizeDemandText(field);if(!f)continue;let score=similarity(q,f)*60;if(f.includes(q)||q.includes(f))score+=35;const ft=new Set(tokens(f));const overlap=qTokens.filter((token)=>ft.has(token)).length;if(qTokens.length)score+=(overlap/qTokens.length)*45;if(qTokens.some((token)=>[...ft].some((candidate)=>candidate.startsWith(token)||token.startsWith(candidate))))score+=8;best=Math.max(best,score)}return Math.min(100,Math.round(best))}
export function suggestDemandCases(input:string,limit=5){const q=normalizeDemandText(input);if(q.length<2)return[];return DEMAND_CASES.map((item)=>({item,score:scoreDemandCase(input,item)})).filter((entry)=>entry.score>=18).sort((a,b)=>b.score-a.score||b.item.homePriority-a.item.homePriority).slice(0,limit)}
export function resolveDemandCase(input:string){return suggestDemandCases(input,1)[0]??null}
export function homeDemandCases(limit=6){return[...DEMAND_CASES].sort((a,b)=>b.homePriority-a.homePriority).slice(0,limit)}
export function findDemandCase(slug:string){return DEMAND_CASES.find((item)=>item.slug===slug)??null}
