-- EU Scout first-party analytics foundation.
-- Isolated from legacy Travel AI and AMM tables by the eu_scout_analytics_* prefix.

create table if not exists public.eu_scout_analytics_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  visitor_id text not null,
  session_id text not null,
  event_name text not null,
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  path text,
  referrer text,
  source text not null default 'web',
  properties jsonb not null default '{}'::jsonb
);

create index if not exists eu_scout_analytics_events_occurred_idx
  on public.eu_scout_analytics_events (occurred_at desc);
create index if not exists eu_scout_analytics_events_session_idx
  on public.eu_scout_analytics_events (session_id, occurred_at);
create index if not exists eu_scout_analytics_events_name_idx
  on public.eu_scout_analytics_events (event_name, occurred_at desc);
create index if not exists eu_scout_analytics_events_properties_idx
  on public.eu_scout_analytics_events using gin (properties);

alter table public.eu_scout_analytics_events enable row level security;

create table if not exists public.eu_scout_analytics_experiments (
  experiment_key text primary key,
  name text not null,
  hypothesis text,
  status text not null default 'draft'
    check (status in ('draft', 'running', 'paused', 'completed')),
  variants jsonb not null default '[{"key":"control","weight":50},{"key":"variant","weight":50}]'::jsonb,
  targeting jsonb not null default '{}'::jsonb,
  primary_metric text not null default 'outbound_click',
  guardrail_metrics jsonb not null default '[]'::jsonb,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.eu_scout_analytics_experiments enable row level security;

create table if not exists public.eu_scout_analytics_experiment_assignments (
  experiment_key text not null references public.eu_scout_analytics_experiments(experiment_key) on delete cascade,
  visitor_id text not null,
  variant_key text not null,
  assigned_at timestamptz not null default now(),
  primary key (experiment_key, visitor_id)
);

alter table public.eu_scout_analytics_experiment_assignments enable row level security;

create table if not exists public.eu_scout_analytics_conversion_postbacks (
  id bigint generated by default as identity primary key,
  network text not null default 'aliexpress',
  transaction_id text not null unique,
  click_id text,
  visitor_id text,
  session_id text,
  product_id text,
  order_value_eur numeric(12,2),
  commission_eur numeric(12,2),
  status text,
  converted_at timestamptz,
  received_at timestamptz not null default now(),
  raw_payload jsonb not null default '{}'::jsonb
);

create index if not exists eu_scout_conversion_click_idx
  on public.eu_scout_analytics_conversion_postbacks (click_id);
create index if not exists eu_scout_conversion_product_idx
  on public.eu_scout_analytics_conversion_postbacks (product_id, converted_at desc);

alter table public.eu_scout_analytics_conversion_postbacks enable row level security;

create or replace view public.eu_scout_funnel_daily as
select
  date_trunc('day', occurred_at)::date as day,
  count(distinct session_id) as sessions,
  count(distinct session_id) filter (where event_name = 'search_started') as search_sessions,
  count(distinct session_id) filter (where event_name = 'search_completed') as completed_search_sessions,
  count(distinct session_id) filter (where event_name = 'product_opened') as product_open_sessions,
  count(distinct session_id) filter (where event_name = 'funnel_step_completed') as committed_funnel_sessions,
  count(distinct session_id) filter (where event_name = 'outbound_intent') as outbound_intent_sessions,
  count(distinct session_id) filter (where event_name = 'outbound_click') as outbound_click_sessions,
  round(
    count(distinct session_id) filter (where event_name = 'outbound_click')::numeric
    / nullif(count(distinct session_id), 0),
    4
  ) as session_to_outbound_rate
from public.eu_scout_analytics_events
group by 1;

create or replace view public.eu_scout_product_kpis_30d as
select
  properties->>'productId' as product_id,
  max(properties->>'productTitle') as product_title,
  count(*) filter (where event_name = 'product_impression') as impressions,
  count(*) filter (where event_name = 'product_opened') as opens,
  count(*) filter (where event_name = 'product_saved') as saves,
  count(*) filter (where event_name = 'outbound_click') as outbound_clicks,
  count(*) filter (where event_name = 'conversion_reported') as conversions,
  round(
    count(*) filter (where event_name = 'outbound_click')::numeric
    / nullif(count(*) filter (where event_name = 'product_impression'), 0),
    4
  ) as impression_to_outbound_rate,
  avg(nullif(properties->>'expectedCommissionEur', '')::numeric)
    filter (where properties ? 'expectedCommissionEur') as avg_expected_commission_eur
from public.eu_scout_analytics_events
where occurred_at >= now() - interval '30 days'
  and properties ? 'productId'
group by properties->>'productId';

create or replace view public.eu_scout_agent_kpis_30d as
select
  coalesce(properties->>'agentRole', 'unknown') as agent_role,
  count(*) as decisions,
  count(*) filter (where properties->>'decision' = 'accept') as accepted,
  count(*) filter (where properties->>'decision' = 'reject') as rejected,
  avg(nullif(properties->>'confidence', '')::numeric)
    filter (where properties ? 'confidence') as avg_confidence
from public.eu_scout_analytics_events
where occurred_at >= now() - interval '30 days'
  and event_name = 'agent_decision'
group by 1;

create or replace view public.eu_scout_campaign_kpis_30d as
select
  coalesce(properties->>'campaign', properties->>'seasonalSection', 'unattributed') as campaign,
  count(*) filter (where event_name = 'seasonal_section_viewed') as section_views,
  count(*) filter (where event_name = 'seasonal_product_selected') as product_selections,
  count(*) filter (where event_name = 'offer_popup_shown') as popup_shows,
  count(*) filter (where event_name = 'offer_popup_accepted') as popup_accepts,
  count(*) filter (where event_name = 'outbound_click') as outbound_clicks
from public.eu_scout_analytics_events
where occurred_at >= now() - interval '30 days'
group by 1;

comment on table public.eu_scout_analytics_events is
  'First-party EU Scout behavioral, funnel, product, campaign and agent telemetry. No raw secrets or payment data.';
comment on table public.eu_scout_analytics_conversion_postbacks is
  'Affiliate conversion postbacks used to calculate realized commission and campaign economics.';
